### ISSUE TITLE
article

### ISSUE THREAD

**Issue by Laura0106** [wannesm/LeuvenMapMatching#19]
Hello dear developers! Is it possible to get an access to your publication : “HMM with Non-Emitting States for Map Matching” ? 
I suppose not only me but all LeuvenMapMatching users will be glad if it will be possible
Thank you!

**Comment by wannesm** [comment]
We only published an abstract on this toolbox, there is no full paper (yet, hopefully). We try to provide extensive documentation (also in the code).
