### ISSUE TITLE
raise Exception(f"Should not happen")

### ISSUE THREAD

**Issue by mattbrown11** [wannesm/LeuvenMapMatching#2]
When I pip install and try to run an example, I get

  File "/usr/local/lib/python2.7/dist-packages/leuvenmapmatching/util.py", line 152
    raise Exception(f"Should not happen")
                                       ^
SyntaxError: invalid syntax

**Comment by mattbrown11** [comment]
Oh, sorry. Didn't realize the library was Python 3 only.

**Comment by wannesm** [comment]
No problem. I updated the setup.py file to make this requirement explicit. There is now also a new pip version + docs available since we pushed a lot of updates in the last two weeks while integrating it into production.

**Comment by mattbrown11** [comment]
Thanks!
