### ISSUE TITLE
'Index' object has no attribute 'upsert'

### ISSUE THREAD

**Issue by creatorLEI** [wannesm/LeuvenMapMatching#24]
Hi, 
I am trying to run the "Create graph using osmread" code,  but I got this error. Do you have any suggestions for this error?
The error is:

AttributeError                            Traceback (most recent call last)
C:\Users\203345~1\AppData\Local\Temp/ipykernel_5252/840127675.py in <module>
     25             map_con.add_edge(node_b, node_a)
     26     if isinstance(entity, osmread.Node):
---> 27         map_con.add_node(entity.id, (entity.lat, entity.lon))
     28 map_con.purge()

~\anaconda\envs\sxpipei3\lib\site-packages\leuvenmapmatching\map\inmem.py in add_node(self, node, loc)
    191             if type(node) is not int:
    192                 raise Exception(f"Rtree index only supports integer keys for vertices")
--> 193             self.rtree.upsert(node, (loc[0], loc[1], loc[0], loc[1]))
    194 
    195     def del_node(self, node):

AttributeError: 'Index' object has no attribute 'upsert'

**Comment by yuanjian24** [comment]
Hi, I also run into the same error while trying `map_con.add_node(nid, (row['y'], row['x']))` using OSM download from OSMNX

**Comment by creatorLEI** [comment]
Thank you, I'll try it. By the way, I also used the method proposed in "Pull requests", which also works.

**Comment by wannesm** [comment]
Thanks for the notification and detailed information. This was an unintended change in this file. I've reverted it back to `insert` in df90155 . This way you can still use `rtree` which is a lot faster than linear search (remember that inmem.py is simple demonstration database. A real db like sqlite/postgress is recommended).
