### ISSUE TITLE
no such module: rtree

### ISSUE THREAD

**Issue by aji1214** [wannesm/LeuvenMapMatching#3]
### Why does this prompt：no such module: rtree

The details are as follows：
  File "D:\Anaconda3\lib\site-packages\leuvenmapmatching\map\sqlite.py", line 393, in all_edges
    c.execute(q, (min_x, max_x, min_y, max_y))

OperationalError: no such module: rtree

**Comment by wannesm** [comment]
To use the SQLite-based DB you need to use a SQLite instance that is compiled with the R*Tree extension: https://www.sqlite.org/rtree.html

Most Python installations don't have this activated by default (e.g. HomeBrew on Mac has it enabled by default). Thus you might need to recompile SQLite.

**Comment by sixyang** [comment]
You can try a higher version of python, I test in Python 3.8.0. It works~
