### ISSUE TITLE
osmnx, Geopandas, DistanceMatcher

### ISSUE THREAD

**Issue by dashSIA** [wannesm/LeuvenMapMatching#31]
Hi,
my question is, how can I combine osmnx, Geopandas and DistanceMatcher together? Can you show me this with an example please? for example with this Data:

[Ponte_Haus.zip](https://github.com/wannesm/LeuvenMapMatching/files/8934157/Ponte_Haus.zip)

I would be happy, if you could give me the answer.

**Comment by wannesm** [comment]
There is an example on how to build a map in the documentation at https://leuvenmapmatching.readthedocs.io/en/latest/usage/openstreetmap.html?highlight=Osmnx#using-osmnx-and-geopandas . Did you try that approach?
