### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by dashSIA** [wannesm/LeuvenMapMatching#32]
hello,
I want to zoom in a specific part of a map to see the results. So I wrote this Code:

 ```
plot_map(map_con,
             matcher=matcher,
             use_osm=True,
             zoom_path=True,
             show_graph=True,
             show_matching=False,
             linewidth=1,
             bb=[-105.0224, 37.9344, -104.9961, 37.9637],
             filename=str(directory / "Foto.png"))

```
But it doesn't work. What am I doing wrong? Is this correct to write bb=[] like this or does it have another format?
I would be thankful for your help.

**Comment by wannesm** [comment]
What is the precise problem? The bb argument will be ignored in this case. The zoom path instruction will set the bounding box to the matched path in the matcher object. Make sure to first run the matching such that the matcher object contains a matched path.

**Comment by dashSIA** [comment]
thank you for your answer. The precise problem is that I want to zoom in my visualization result to see a specific part of a map. For Example if I have my map matching result for 100 km, how can I make a zoom and see how the map matching works for a specific road part?
I hope it is clear now. I would be thankful for answers.

**Comment by wannesm** [comment]
Set `zoom_path` to False. Then the `bb` argument is used.

**Comment by dashSIA** [comment]
I set `zoom_path` to False but it doesn't work. I can read this in Console: 

```
Lowered zoom level to keep map size reasonable. (z = 15)
Lowered zoom level to keep map size reasonable. (z = 15)
```

The first one is for the normal visualization without `bb`  and the second one is for the zoom in with `bb`. Apparently the program can't use bb to zoom in. How can I solve this problem?

**Comment by wannesm** [comment]
This comment should have no real impact. It's a message from the package that downloads tiles, https://github.com/rossant/smopy , to indicate that you reached the maximal zoom level. But it only impacts the tiles.
