### ISSUE TITLE
Map object has missing edges when importing from OSMNX

### ISSUE THREAD

**Issue by Yozpoz64** [wannesm/LeuvenMapMatching#34]
Hi,

Something is going wrong when I am converting an OSMNX graph to a map object. I noticed the matching was a bit off, and when I compare the original graph to the map object I can see it is very simplified - edges simply connect all nodes.

Original OSMNX graph:
![3cab033e-2369-4115-8ec4-29e057033ed4](https://user-images.githubusercontent.com/19566908/180590631-ea7f020b-1eb0-45b8-ba99-0f099684e64b.png)

Map object after adding nodes and edges from original graph
![b1bfe1c8-940c-4b38-8f17-dc2e6e13c69b](https://user-images.githubusercontent.com/19566908/180590630-72174250-fafa-4404-b915-a7f29415ac78.png)

I noted that there are about 1000 less edges in the map object than the original graph. The number of nodes is identical. I am using "Approach 2" in the [examples](https://leuvenmapmatching.readthedocs.io/en/latest/usage/openstreetmap.html) to add nodes and edges to an InMemMap. No errors are thrown when looping through the edges and using `map_con.add_edge()`, and the loop runs through all edges of the original graph. But when I count the edges with `len(list(map_con.all_nodes()))` immediately after the loop it is lower by around 1000. Is this something to do with OSMNX having linestring geometry between edges while the map object is a straight line from node to node? If so, is there a way to include the linestring geometry?

Am I missing something here? Any help would be greatly appreciated. The matching works fantastically for the incorrect network, so I am really hoping I can get it working on the original!

Here is the code block for adding the graph edges, nodes to the map object:
```python
from leuvenmapmatching.map.inmem import InMemMap
from leuvenmapmatching.util.gpx import gpx_to_path

graph_proj = ox.project_graph(graph)  # graph of downloaded OSM roads

map_con = InMemMap("myosm", use_latlon=True, 
        use_rtree=False, index_edges=False)

nodes, edges = ox.graph_to_gdfs(graph_proj, nodes=True, edges=True)

nodes_proj = nodes.to_crs("EPSG:4326")
edges_proj = edges.to_crs("EPSG:4326")

for nid, row in nodes_proj.iterrows():
    map_con.add_node(nid, (row['lat'], row['lon']))

for nid1, nid2, _ in graph.edges:
    map_con.add_edge(nid1, nid2)

print(graph_proj.number_of_edges())  # gives 28440
print(len(list(map_con.all_edges())))  # gives 27309

```

**Comment by wannesm** [comment]
Thanks for reporting. That's an omission in the documentation. The call to `graph_from_place` requires the argument `simplify=False` (and similar if you would be using `graph_from_point`). The default is True and eliminates all points on the road segment reducing it to a straight line in the current example.

Thus:

        graph = ox.graph_from_place('Leuven, Belgium', network_type='drive', simplify=False)

**Comment by Yozpoz64** [comment]
> Thanks for reporting. That's an omission in the documentation. The call to `graph_from_place` requires the argument `simplify=False` (and similar if you would be using `graph_from_point`). The default is True and eliminates all points on the road segment reducing it to a straight line in the current example.
> 
> Thus:
> 
> ```
>     graph = ox.graph_from_place('Leuven, Belgium', network_type='drive', simplify=False)
> ```

Thank you very much, this worked!
