### ISSUE TITLE
SimpleMatcher math domain error

### ISSUE THREAD

**Issue by Hydroxycoumarin** [wannesm/LeuvenMapMatching#35]
I meet the problem when I wanna use SimpleMatcher. I don't understand why cos(d) raises the error unless the input is none or something similiar.
![image](https://user-images.githubusercontent.com/62802261/181513867-2aedbf78-2a64-4f6e-91df-51a66550dbd8.png)

**Comment by wannesm** [comment]
I would suspect it is the asin function that throws the error.  Based on this information it is hard to deduce the error. Any chance you can trigger this error again and print `lat1`, `lon1`, `bearing`, `dist` and `earth_radius`?

**Comment by Hydroxycoumarin** [comment]
The error can be triggered again but I don't know how to print the variables since they are local :(

**Comment by wannesm** [comment]
The file listed in the path can be opened and edited. Thus if you open the file `~/anaconda3/env/.../dist_latlon.py` you can add after line 203: `print(lat1, lon1, bearing, dist, earth_radius)`. It might print a lot if the error is occurring late in the process but only the last one is relevant. And then remove this line again afterwards.

**Comment by Hydroxycoumarin** [comment]
Copy! Really appreciate the suggestion, I will try it tomorrow:)

**Comment by Hydroxycoumarin** [comment]
I have found the problem, the dist and d = inf because I didn't set max_dist_init and max_dist. It seems there are some essential parameters needed to run SimpleMatcher?

**Comment by Hydroxycoumarin** [comment]
It seems max_lattice_width is essential.

**Comment by Hydroxycoumarin** [comment]
The simple matcher is not as efficient as the HMM matcher. Although the bug reappeared later (ValueError even though the parameters were set), I decided to use the HMM matcher and not deal with the simple matcher anymore.
