### ISSUE TITLE
Can the matcher handle the case when there are multiple edges between two nodes?

### ISSUE THREAD

**Issue by csjiezhao** [wannesm/LeuvenMapMatching#40]
In osm, `u` and `v` represent the start and end points respectively, and there is also a field `key` to represent the multiple edges between `u` and `v`. How can we use the information of `key` in the matcher?

**Comment by wannesm** [comment]
The assumption is that between two nodes, there is only a straight edge (similar as in the openstreetmap database). Two edges connecting the same `u` and `v` would thus represent the exact same edge. Therefore, the key is not used for the matching.

**Comment by csjiezhao** [comment]
> The assumption is that between two nodes, there is only a straight edge (similar as in the openstreetmap database). Two edges connecting the same `u` and `v` would thus represent the exact same edge. Therefore, the key is not used for the matching.

Thanks for your reply~ Would you tell me if there is another matching algorithm that can handle multiple edges between nodes?

**Comment by wannesm** [comment]
To be clear. It is not supported explicitly in the matchers that are available but you can by extending the matchers and supporting it in a custom map connector (it’s a simple wrapper on top of a database).  If the matcher does not know about any difference between two edges, there is no advantage in representing them. Eg the DistanceMatcher could take road type into account if you adapt the probability function to do so. 

 As far as I’m aware this is quite similar across different toolboxes. Using custom information requires adding some custom logic to the matcher. The ones available are those present in the most used papers and thus typically rather generic.
