### ISSUE TITLE
Does BaseMatcher.match(...) support parallel execution, for instance using multiprocessing?

### ISSUE THREAD

**Issue by JunzeYang** [wannesm/LeuvenMapMatching#54]
Hello, developers,

I wonder if the [BaseMatcher.match(...)](https://leuvenmapmatching.readthedocs.io/en/latest/_modules/leuvenmapmatching/matcher/base.html#BaseMatcher.match) function supports parallel execution using [multiprocessing](https://docs.python.org/3/library/multiprocessing.html). For example, with a large GPS dataset `gps_df`, I want to perform parallel map matching tasks based on the column `vehicle_id`. Below is a sample code snippet:

```ruby

from multiprocessing import Pool
from leuvenmapmatching.map.inmem import InMemMap
from leuvenmapmatching.matcher.distance import DistanceMatcher
...

def map_matching(map_con, traj_df):
    path = list(zip(traj_df.geometry.y, traj_df.geometry.x, traj_df['Time']))
    matcher = DistanceMatcher(
        map_con=map_con,
        ...
    )
    state, _ = matcher.match(path, unique=True)
    ...
    return state

if __name__ == "__main__":
    gps_df = gpd.read_file(...)
    map_con = InMemMap(...)
    veh_id_list = list(gps_df['vehicle_id'].unique())
    with Pool(8) as p:
        args = [(map_con, gps_df[gps_df['vehicle_id'] == veh_id]) for veh_id in veh_id_list]
        state_list = p.starmap(map_matching, args)

```
However, it returns an empty `state_list` and does not raise any errors. I've checked and confirmed that the `state` for all `vehicle_id` are not empty. Additionally, when I remove the `matcher.match(...)` in the `map_matching` function, the results of the parallel execution are correct, indicating that this issue is not with other parts of the `map_matching` function. Is there a way to resolve it? 

Thanks a lot!

**Comment by wannesm** [comment]
The matcher has no global variables, thus I see no reason why that would cause problems. I do wonder whether the pickling is a problem. We did not foresee the map object to be picklable, while this is what multiprocessing does for its arguments. How did you check that `state` is not empty, by replacing pool with a for loop?

**Comment by wannesm** [comment]
To add to that. I don't think pickling an entire map is a good idea, thus not something on our planning. For this we use databases like the SQLite wrapper and thus also create a new map instance (all reading the same database).

**Comment by JunzeYang** [comment]
Thank you very much. As you said, I've checked the value of `state` with a for loop. I found the issue indeed lies in the map instance. If each subprocess shares the same `map_con` instance, the [‎map.edges_closeto](https://github.com/wannesm/LeuvenMapMatching/blob/master/leuvenmapmatching/matcher/base.py#L688) in the [‎BaseMatcher._create_start_nodes](https://github.com/wannesm/LeuvenMapMatching/blob/master/leuvenmapmatching/matcher/base.py#L671) will return an empty node generator, resulting in [an empty list](https://github.com/wannesm/LeuvenMapMatching/blob/master/leuvenmapmatching/matcher/base.py#L606) for `state`. Your suggestion to create a new `map_con` within the `map_matching` function really works for me. Thanks again!
