### ISSUE TITLE
b'no arguments

### ISSUE THREAD

**Issue by CateDeku** [wannesm/LeuvenMapMatching#6]
Hi,
i'm trying to run the example that is posted here:
https://leuvenmapmatching.readthedocs.io/en/latest/usage/openstreetmap.html

anyway i keep getting this erros: RuntimeError: b'no arguments in initialization list.
Any suggestion to fix it? Here's the code
![image](https://user-images.githubusercontent.com/52274927/63528469-4a156280-c503-11e9-9c9a-c3804bc422f1.png)

**Comment by wxl112** [comment]
dang! I run  across the same question, have you fixed it yet?

**Comment by wannesm** [comment]
Did you use the latest version of leuvenmapmatching and pyproj? This seems related to changes in PROJ and thus pyproj that was address in 1b6f0b69eb6e837dd50da9fde92fa115f07b578a.

**Comment by wxl112** [comment]
> 

dude,I'm so appreciated that your advice and ended up proving it's really helpful, thanks a lot!
best wishes

**Comment by wannesm** [comment]
Thanks for the update. I'll close this issue. 

Note that the matcher now also has a recommended `max_lattice_width=5` option to speed up the matching.
